'use strict';
const $=s=>document.querySelector(s);
const dialog=$('#intake-dialog');
let questions=window.YAH_INTAKE_QUESTIONS;
let answers=Array(questions.length).fill(''),step=0,returnFocus=null;
function bubble(text,user=false){const el=document.createElement('div');el.className='bubble'+(user?' user':'');el.textContent=text;$('#conversation').append(el)}
function render(){const done=step===questions.length;$('#intake-form').hidden=done;$('#summary').hidden=!done;$('#conversation').hidden=done;$('#progress-bar').style.width=((done?questions.length:step+1)/questions.length*100)+'%';$('#progress-label').textContent=done?'Uw gespreksvoorbereiding is klaar':`Vraag ${step+1} van ${questions.length}`;
 if(done){$('#summary-text').value=summary();$('#summary-text').focus();return;}
 $('#conversation').replaceChildren();for(let i=Math.max(0,step-1);i<step;i++){bubble(questions[i].text);bubble(answers[i],true)}
 bubble(questions[step].text);
 $('#answer').value=answers[step];$('#answer-label').textContent=questions[step].label;$('#suggestions').replaceChildren();questions[step].choices.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='chip';b.textContent=c;b.onclick=()=>{$('#answer').value=c;$('#answer').focus()};$('#suggestions').append(b)});$('#back').disabled=step===0;$('#conversation').scrollTop=$('#conversation').scrollHeight;$('#answer').focus();}
function summary(){let text='GESPREKSVOORBEREIDING — YAH-ADVIES\n\n'+questions.map((q,i)=>q.label+'\n'+(answers[i]||'Nog onbekend')).join('\n\n');text+='\n\nVRAGEN VOOR HET GESPREK\n1. Wat is het belangrijkste gewenste resultaat en wanneer is de opdracht geslaagd?\n2. Welke informatie en betrokkenen zijn beschikbaar?\n3. Welke scope, aanpak, planning en vergoeding passen bij de vraag?';const unknown=questions.filter((q,i)=>!answers[i]||answers[i]==='Nog onbekend').map(q=>q.label);if(unknown.length)text+='\n\nNOG TE VERHELDEREN\n'+unknown.join(', ');text+='\n\nDit is een door u ingevulde voorbereiding, geen technische diagnose, offerte of bevestigde afspraak. YAH-Advies beoordeelt of en hoe het vraagstuk bij de dienstverlening past.';return text;}
function start(topic,support){const requested=/werving|detachering/i.test(topic||"")?window.YAH_RECRUITMENT_QUESTIONS:window.YAH_INTAKE_QUESTIONS;if(step===0&&requested!==questions){questions=requested;answers=Array(questions.length).fill("");}$('#intake-title').textContent=questions===window.YAH_RECRUITMENT_QUESTIONS?'Vertel ons over uw personeelsvraag.':'Vertel ons over uw project.';const sf=$('#send-intake');if(sf)sf.dataset.subject=questions===window.YAH_RECRUITMENT_QUESTIONS?'Personeelsvraag via yah-advies.nl':'Projectaanvraag via yah-advies.nl';if(!dialog.open){returnFocus=document.activeElement;dialog.showModal()}if(topic&&step===0)answers[0]=topic;if(support&&step===0&&questions===window.YAH_INTAKE_QUESTIONS)answers[3]=support;render();}
document.querySelectorAll('[data-intake]').forEach(b=>b.onclick=()=>start(b.dataset.topic,b.dataset.support));$('#close-intake').onclick=()=>dialog.close();dialog.addEventListener('close',()=>returnFocus?.focus());
$('#intake-form').onsubmit=e=>{e.preventDefault();const a=$('#answer').value.trim();if(!a){$('#answer').setCustomValidity('Vul een antwoord in of kies Nog onbekend.');$('#answer').reportValidity();return;}answers[step]=a;step++;render()};$('#answer').oninput=()=>$('#answer').setCustomValidity('');$('#skip').onclick=()=>{answers[step]='Nog onbekend';step++;$('#answer').setCustomValidity('');render()};$('#back').onclick=()=>{if(step>0){answers[step]=$('#answer').value.trim();step--;$('#answer').setCustomValidity('');render()}};
$('#edit-answers').onclick=()=>{step=0;render()};$('#restart').onclick=()=>{answers=Array(questions.length).fill('');step=0;render()};$('#download').onclick=()=>{const text=$('#summary-text').value;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='YAH-advies-gespreksvoorbereiding.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
// Samenvatting via het eigen e-mailprogramma van de bezoeker; de site verstuurt zelf niets.
const mailBtn=$('#mail-summary');if(mailBtn)mailBtn.addEventListener('click',()=>{const rec=questions===window.YAH_RECRUITMENT_QUESTIONS;const subj=rec?'Personeelsvraag via yah-advies.nl':'Projectvraag via yah-advies.nl';let blocks=$('#summary-text').value.split(/\n\n+/).filter(b=>!/^Dit is een door u ingevulde voorbereiding/.test(b));const ci=blocks.findIndex(b=>/contact/i.test(b.split('\n')[0]));if(ci>0)blocks.unshift(blocks.splice(ci,1)[0]);const note='\n\n[Ingekort: voeg het gedownloade tekstbestand als bijlage toe voor de volledige voorbereiding.]';const enc=b=>'mailto:info@yah-advies.nl?subject='+encodeURIComponent(subj)+'&body='+encodeURIComponent(b);let body=blocks.join('\n\n');if(enc(body).length>1900){while(blocks.length>1&&enc(blocks.join('\n\n')+note).length>1900)blocks.pop();body=blocks.join('\n\n')+note;while(enc(body).length>1900)body=body.slice(0,-40)}mailBtn.href=enc(body)});
$('.menu-toggle').onclick=()=>{const on=$('#nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String(on))};document.querySelectorAll('nav a,nav button').forEach(a=>a.addEventListener('click',()=>{$('#nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')}));$('#privacy-button').onclick=()=>$('#privacy-dialog').showModal();$('#close-privacy').onclick=()=>$('#privacy-dialog').close();
if(document.modelContext?.registerTool){try{const lifecycle=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'start_yah_intake',title:'Start YAH-advies intake',description:'Open de lokale intakevoorbereiding. Verstuurt geen gegevens en maakt geen afspraak.',inputSchema:{type:'object',properties:{topic:{type:'string',maxLength:200}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='topic')||('topic'in input&&(typeof input.topic!=='string'||input.topic.length>200)))throw new Error('Ongeldig onderwerp');start(input.topic);return{opened:true,step:step+1,sent:false}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
